### ISSUE TITLE
Validação na controller auth e na action login 

### ISSUE THREAD

**Issue by ChrystianDeMatos** [nsosoares/NS.Veterinary#1]
As validações ao chamar a action login estão sendo feita antes de rodar a action e não ao validar na action
[https://github.com/nsosoares/NS.Veterinary/blob/aa774c59e2f10446d5e3716a5dd1c33353b16aad/NS.Veterinaria.Api/Controllers/AuthController.cs#L60](url)

**Comment by ChrystianDeMatos** [comment]
@nsosoares

**Comment by nsosoares** [comment]
Já foi solucionado! O problema estava em que o atributo ApiController realiza as validações da model state antes de chamar a action assim não deixando ter um custom response @ChrystianDeMatos
